server:
   port: 8768
spring:
   application:
      name: hystrix-zuul-aggregation
zuul:
   routes:
      api-a:
         path: /api-a/**
         serviceId: article-service
      api-b:
         path: /api-b/**
         serviceId: hello-service
   ignored-services: '*'
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
feign:
   hystrix:
      enabled: true
hystrix:
   command:
      ArticleService#getAllArticles():
         execution:
            isolation: #getAllArticles():   # 针对getAllArticles方法生效
               thread:
                  timeoutInMilliseconds: 100 # 配置hystrix 100ms超时
         circuitBreaker:
            requestVolumeThreshold: 3 # 将断路器10s请求阈值改为3次